export const DUNGEON_THEME_MODE_THEME = "theme";
export const DUNGEON_THEME_MODE_SCRATCH = "scratch";

export const DUNGEON_SCALE_ROOM_RANGES = Object.freeze({
  small: Object.freeze({ min: 4, max: 6, fallback: 5 }),
  medium: Object.freeze({ min: 7, max: 10, fallback: 8 }),
  large: Object.freeze({ min: 11, max: 16, fallback: 12 }),
});

export const DUNGEON_COMPLEXITY_ROOM_BONUSES = Object.freeze({
  simple: -1,
  standard: 0,
  complex: 2,
});

export const DUNGEON_THEMES = Object.freeze([
  Object.freeze({
    id: "generic-dark-location",
    name: "Generic Dark Location",
    sourceAnchorIds: [],
    defaultArchetype: "cursed_location",
    allowedArchetypes: Object.freeze([
      "cursed_location",
      "ruined_sanctum",
      "haunted_crypt",
      "corrupted_house",
    ]),
    forbiddenArchetypes: Object.freeze([]),
    mapTypeBias: Object.freeze(["Crypt", "Ruins", "Chapel"]),
    roomTypeBias: Object.freeze([
      "threshold",
      "passage",
      "hazard room",
      "clue room",
      "setpiece",
      "reward room",
      "final chamber",
    ]),
    roomRoleSequence: Object.freeze([
      "entrance",
      "transition",
      "discovery",
      "hazard",
      "clue",
      "reward",
      "climax",
      "exit",
    ]),
    sensoryPalette: Object.freeze(["cold air", "stale dust", "distant dripping", "uneven silence"]),
    visualPalette: Object.freeze(["old stains", "broken thresholds", "darkened corners", "marked walls"]),
    hazardBias: Object.freeze(["unstable terrain", "contaminated air", "ritual pressure"]),
    rewardBias: Object.freeze(["forbidden relic", "useful clue", "marked treasure"]),
    layoutBias: Object.freeze({ density: "standard", connectionStyle: "branching" }),
  }),
  Object.freeze({
    id: "sedlec-ossuary",
    name: "Sedlec Ossuary",
    sourceAnchorIds: Object.freeze(["sedlec-ossuary"]),
    defaultArchetype: "ossuary_chapel_with_crypt",
    allowedArchetypes: Object.freeze([
      "ossuary_chapel",
      "crypt_chapel",
      "catacomb",
      "reliquary_vault",
      "subterranean_charnel_house",
      "ossuary_chapel_with_crypt",
    ]),
    forbiddenArchetypes: Object.freeze([
      "forest",
      "swamp",
      "wizard_tower",
      "open_wilderness",
      "bandit_camp",
    ]),
    mapTypeBias: Object.freeze(["Chapel", "Crypt", "Ruins"]),
    roomTypeBias: Object.freeze([
      "bone-lit vestibule",
      "skull-lined corridor",
      "ossuary gallery",
      "crypt chapel",
      "reliquary niche",
      "mass grave",
      "sacristy",
      "sealed catacomb",
      "bone archive",
    ]),
    roomRoleSequence: Object.freeze([
      "entrance",
      "transition",
      "discovery",
      "hazard",
      "clue",
      "reward",
      "secret",
      "climax",
      "exit",
    ]),
    sensoryPalette: Object.freeze([
      "cold incense",
      "bone dust",
      "damp limestone",
      "old wax",
      "muffled hymns",
    ]),
    visualPalette: Object.freeze([
      "skull garlands",
      "bone chandeliers",
      "counted dead",
      "devotional remains",
      "candle niches",
    ]),
    hazardBias: Object.freeze([
      "collapsing bone wall",
      "desecrated relic",
      "suffocating dust",
      "unstable ossuary shelf",
    ]),
    rewardBias: Object.freeze([
      "saint relic",
      "ossuary key",
      "forbidden prayer",
      "bone icon",
    ]),
    layoutBias: Object.freeze({ density: "compact", connectionStyle: "ritual_path", verticality: "crypt_below_chapel" }),
  }),
  Object.freeze({
    id: "decomposition",
    name: "Decomposition",
    sourceAnchorIds: Object.freeze(["decomposition"]),
    defaultArchetype: "rotting_understructure",
    allowedArchetypes: Object.freeze([
      "rotting_understructure",
      "corpse_softened_cave",
      "plague_cellar",
      "sinking_crypt",
      "organic_ruin",
    ]),
    forbiddenArchetypes: Object.freeze(["clean_chapel", "open_wilderness", "wizard_tower"]),
    mapTypeBias: Object.freeze(["Crypt", "Cave", "Mine", "Ruins"]),
    roomTypeBias: Object.freeze([
      "soft-floored tunnel",
      "gas pocket",
      "wet archive",
      "bloated chamber",
      "drainage crypt",
      "collapse room",
    ]),
    roomRoleSequence: Object.freeze(["entrance", "transition", "hazard", "clue", "hazard", "reward", "climax"]),
    sensoryPalette: Object.freeze(["sweet rot", "wet cloth", "swollen wood", "grave wax", "warm gas"]),
    visualPalette: Object.freeze(["skin slippage", "seeping joints", "bloated doors", "soft stone"]),
    hazardBias: Object.freeze(["toxic gas", "collapsing floor", "disease cloud", "slick rot"]),
    rewardBias: Object.freeze(["preserved key", "grave-wax charm", "contaminated medicine"]),
    layoutBias: Object.freeze({ density: "claustrophobic", connectionStyle: "soft_loops" }),
  }),
  Object.freeze({
    id: "towers-of-silence",
    name: "Towers of Silence",
    sourceAnchorIds: Object.freeze(["towers-of-silence"]),
    defaultArchetype: "exposure_tower_and_crypt",
    allowedArchetypes: Object.freeze([
      "exposure_tower",
      "ritual_courtyard",
      "sky_burial_crypt",
      "vulture_shrine",
      "exposure_tower_and_crypt",
    ]),
    forbiddenArchetypes: Object.freeze(["forest", "noble_house", "wizard_tower"]),
    mapTypeBias: Object.freeze(["Ruins", "Chapel", "Crypt"]),
    roomTypeBias: Object.freeze([
      "ritual boundary",
      "exposure court",
      "vulture gallery",
      "sun-bleached stair",
      "purity chamber",
      "bone well",
    ]),
    roomRoleSequence: Object.freeze(["entrance", "ritual", "hazard", "transition", "clue", "climax", "exit"]),
    sensoryPalette: Object.freeze(["dry heat", "wingbeats", "sun-warmed stone", "ritual silence"]),
    visualPalette: Object.freeze(["circling birds", "open stone", "sun-bleached bone", "chalk boundary"]),
    hazardBias: Object.freeze(["falling birds", "sun exposure", "ritual contamination", "open drop"]),
    rewardBias: Object.freeze(["purity token", "ritual knife", "sun-bleached omen"]),
    layoutBias: Object.freeze({ density: "open_center", connectionStyle: "radial" }),
  }),
  Object.freeze({
    id: "the-mist",
    name: "The Mist",
    sourceAnchorIds: Object.freeze(["the-mist"]),
    defaultArchetype: "fogbound_threshold_site",
    allowedArchetypes: Object.freeze([
      "fogbound_outpost",
      "abandoned_station",
      "sealed_village_edge",
      "mist_breached_ruin",
      "fogbound_threshold_site",
    ]),
    forbiddenArchetypes: Object.freeze(["ossuary_chapel", "clean_crypt", "sunlit_courtyard"]),
    mapTypeBias: Object.freeze(["Ruins", "Noble House", "Mine"]),
    roomTypeBias: Object.freeze([
      "fog-return corridor",
      "visibility break",
      "sealed supply room",
      "panic chamber",
      "glass threshold",
      "creature pressure point",
    ]),
    roomRoleSequence: Object.freeze(["entrance", "transition", "clue", "hazard", "loop", "climax", "exit"]),
    sensoryPalette: Object.freeze(["white silence", "wet glass", "muffled voices", "distant shapes"]),
    visualPalette: Object.freeze(["white wall", "shapes in fog", "condensed windows", "unreadable distance"]),
    hazardBias: Object.freeze(["lost visibility", "false return", "panic pressure", "unknown creature path"]),
    rewardBias: Object.freeze(["flare cache", "radio clue", "sealed route key"]),
    layoutBias: Object.freeze({ density: "fragmented", connectionStyle: "false_loops" }),
  }),
  Object.freeze({
    id: "wolf-spiders",
    name: "Wolf Spiders",
    sourceAnchorIds: Object.freeze(["wolf-spiders"]),
    defaultArchetype: "spider_nest_lair",
    allowedArchetypes: Object.freeze([
      "spider_nest_lair",
      "burrow_network",
      "infested_cellar",
      "hunting_corridor_complex",
    ]),
    forbiddenArchetypes: Object.freeze(["ossuary_chapel", "noble_ballroom", "open_courtyard"]),
    mapTypeBias: Object.freeze(["Cave", "Mine", "Noble House", "Ruins"]),
    roomTypeBias: Object.freeze([
      "webbed threshold",
      "egg chamber",
      "hunting corridor",
      "molting room",
      "victim cache",
      "brood nest",
    ]),
    roomRoleSequence: Object.freeze(["entrance", "transition", "ambush", "hazard", "reward", "climax", "exit"]),
    sensoryPalette: Object.freeze(["leg vibration", "dry silk", "eye shine", "tiny scatter"]),
    visualPalette: Object.freeze(["egg sacs", "carried young", "webbed victims", "dark corners"]),
    hazardBias: Object.freeze(["web restraint", "ambush path", "brood scatter", "sticky floor"]),
    rewardBias: Object.freeze(["silk bundle", "venom sac", "survivor clue"]),
    layoutBias: Object.freeze({ density: "tangled", connectionStyle: "webbed_branches" }),
  }),
]);
