import {
  asArray,
  clone,
  slugify,
} from "./studio-component-normalizers.js";
import {
  buildStudioComponentFromTemplate,
  buildStudioComponentsFromTemplate,
} from "./studio-component-templates.js";

export const EMPTY_DRAFT = Object.freeze({
  id: "new-inspiration",
  title: "New Inspiration",
  status: "draft",
  packId: "new-content-pack",
  sourceAnchor: {
    id: "new-inspiration",
    label: "New Inspiration",
    type: "Source Anchor",
    status: "draft",
    workflows: [],
    sourceTypes: [],
    themes: [],
    motifs: [],
    horror: [],
    summary: "",
  },
  inspiration: {
    id: "inspiration-new-inspiration",
    title: "New Inspiration",
    label: "New Inspiration",
    contentType: "source-inspiration-card",
    status: "draft",
    workflows: ["inspiration-archive"],
    sourceAnchors: ["new-inspiration"],
    sourceTypes: [],
    themes: [],
    motifs: [],
    horror: [],
    summary: "",
    narrative: "",
    caption: "",
    media: {
      imageKey: "",
      imageUrl: "",
      imageNote: "",
    },
  },
  components: [],
  monsterGrafts: [],
  locationComponents: [],
  locationRegions: [],
  metadata: {
    moduleRole: "studio-draft",
  },
});

export function getAutogeneratedIdentityIds(title) {
  const sourceAnchorId = slugify(title);
  return {
    moduleId: sourceAnchorId,
    sourceAnchorId,
    inspirationId: `inspiration-${sourceAnchorId}`,
  };
}

export function syncDraftIdentityIds(nextDraft, title = nextDraft.title) {
  const ids = getAutogeneratedIdentityIds(title);
  const previousSourceAnchorId = nextDraft.sourceAnchor?.id;
  nextDraft.id = ids.moduleId;
  nextDraft.sourceAnchor = nextDraft.sourceAnchor || {};
  nextDraft.sourceAnchor.id = ids.sourceAnchorId;
  nextDraft.inspiration = nextDraft.inspiration || {};
  nextDraft.inspiration.id = ids.inspirationId;
  nextDraft.inspiration.sourceAnchors = [ids.sourceAnchorId];
  nextDraft.components = asArray(nextDraft.components).map((component) => ({
    ...component,
    sourceAnchors: asArray(component.sourceAnchors).length && previousSourceAnchorId
      ? asArray(component.sourceAnchors).map((sourceAnchorId) => sourceAnchorId === previousSourceAnchorId ? ids.sourceAnchorId : sourceAnchorId)
      : [ids.sourceAnchorId],
  }));
}

export function getModuleComponentGroups(draft) {
  const components = asArray(draft.components);
  return {
    all: components,
    "monster-graft": components.filter((component) => component.contentType === "monster-graft"),
    "location-component": components.filter((component) => component.contentType === "location-component"),
    "location-region": components.filter((component) => component.contentType === "location-region"),
  };
}

export function normalizeModuleForDraft(module) {
  const draft = clone(module || EMPTY_DRAFT);
  const sourceAnchorId = draft.sourceAnchor?.id || draft.id || slugify(draft.title);

  draft.id = draft.id || sourceAnchorId;
  draft.title = draft.title || draft.sourceAnchor?.label || draft.inspiration?.title || sourceAnchorId;
  draft.status = draft.status || draft.sourceAnchor?.status || draft.inspiration?.status || "draft";
  draft.packId = draft.packId || "core-cruor";
  draft.sourceAnchor = {
    ...EMPTY_DRAFT.sourceAnchor,
    ...(draft.sourceAnchor || {}),
    id: sourceAnchorId,
  };
  draft.inspiration = {
    ...EMPTY_DRAFT.inspiration,
    ...(draft.inspiration || {}),
    sourceAnchors: asArray(draft.inspiration?.sourceAnchors).length
      ? asArray(draft.inspiration?.sourceAnchors)
      : [sourceAnchorId],
    media: {
      ...EMPTY_DRAFT.inspiration.media,
      ...(draft.inspiration?.media || {}),
    },
  };
  draft.components = asArray(draft.components);
  draft.monsterGrafts = draft.components.filter((component) => component.contentType === "monster-graft");
  draft.locationComponents = draft.components.filter((component) => component.contentType === "location-component");
  draft.locationRegions = draft.components.filter((component) => component.contentType === "location-region");
  draft.metadata = { ...(draft.metadata || {}) };

  return draft;
}

export function buildComponentTemplate(templateId, draft) {
  return buildStudioComponentFromTemplate(templateId, normalizeModuleForDraft(draft));
}

export function buildComponentTemplates(templateId, draft) {
  return buildStudioComponentsFromTemplate(templateId, normalizeModuleForDraft(draft));
}
